import type { Metadata } from "next";
import { Roboto, Oswald } from '@next/font/google';
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/whatsappButton";

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700"],
  variable: "--font-oswald",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700","900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "My Personal Gym",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${roboto.variable} w-full max-w-[1920px] mx-auto relative overflow-x-hidden`}
      >
        <div className="bg-gradient-to-b from-black to-gray-900 min-h-screen">
          <Header />
          {children}
          <Footer />
          <WhatsAppButton />
        </div>
      </body>
    </html>
  );
}
